### ISSUE TITLE
Door stays unlocked

### ISSUE THREAD

**Issue by doncuco** [imhotep/hass-unifi-access#67] opened 2024-08-31 10:03 UTC
**Describe the bug**
I use the integration to open my door. 
I have a door that automatic locks itself.
So I just need an impulse to open it. 
Job done.
The unifi access app works fine.
In home assistant the lock stays unlocked.
I need to reload the integration so that the state gets reset to locked and I can unlock the door again.
Manually changing things doesn't work.
I got the problem with the last update of the integration.

**Which Hub are you using**
Unifi Access Hub

**Screenshots**
![image](https://github.com/user-attachments/assets/2e24c8ba-2c95-47c9-a1aa-928dcbaff821)

**Versions:**
 - Home Assistant version 2024.8.3
 - Unifi Access version 2.2.11
 - Unifi Access Integration version 1.2

**Home Assistant DEBUG logs (MANDATORY)**

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.unifi_access.lock
Quelle: custom_components/unifi_access/lock.py:82
Integration: Unifi Access
Erstmals aufgetreten: 00:33:12 (19 Vorkommnisse)
Zuletzt protokolliert: 11:58:14

Locking is not supported by Unifi Access API

**Comment by imhotep** [comment] 2024-08-31 16:32
Duplicate of #64

**Closed by imhotep** 2024-08-31 16:32 UTC
