### ISSUE TITLE
No Longer Logging Doorbell Presses or Exit

### ISSUE THREAD

**Issue by JDogg016** [imhotep/hass-unifi-access#42] opened 2024-06-24 08:59 UTC
This is the log I receive

Logger: custom_components.unifi_access.coordinator
Source: helpers/update_coordinator.py:318
integration: Unifi Access
First occurred: June 22, 2024 at 1:11:10 PM (271 occurrences)
Last logged: 10:51:24 AM

Timeout fetching Unifi Access Coordinator data

**Comment by jasonhollis** [comment] 2024-06-25 04:55
I'm sure it's a stupid question but what do I need to do to get to the event data for the custom component?

I have 

logger:
  default: info
  logs:
    custom_components.unifi_access.coordinator: info
    
Setup in the config.yaml.  But I don't see anything in the main log.  
![CleanShot 2024-06-25 at 14 50 07@2x](https://github.com/imhotep/hass-unifi-access/assets/19743618/b2fb164f-ffd2-4c11-95b2-6baca722ef81)
If I enable debug logging in the integration I'm also not seeing the event data there either.  @JDogg016 as Dogg has mentioned I'm also not getting anything from the G2 Pro doorbell.  

![CleanShot 2024-06-25 at 14 53 58@2x](https://github.com/imhotep/hass-unifi-access/assets/19743618/65cae31e-54e7-437b-bbf3-1ae629b0ba5b)

**Comment by JDogg016** [comment] 2024-07-04 18:41
Correct.  There is nothing in any log when an 'exit_event' occurs.  Thus the problem.  Until about 1 months ago this worked allowing you to trigger automations on exit_events (as opposed to entry_events)

**Comment by imhotep** [comment] 2024-07-09 21:11
@JDogg016 can you share actual logs? What you posted seems to be coming from your home assistant front-end. I cannot reproduce the issue in my setup.

**Comment by JDogg016** [comment] 2024-07-10 10:49
When I enable debug logging, I get the following logs when I unlock the door.

`2024-07-10 06:41:10.675 INFO (SyncWorker_17) [custom_components.unifi_access.hub] Getting door updates from Unifi Access https://192.168.7.1:12445 Use Polling True
2024-07-10 06:41:10.756 DEBUG (MainThread) [custom_components.unifi_access.coordinator] Finished fetching Unifi Access Coordinator data in 0.080 seconds (success: True)
`

To be clear.  This attribute has not fired since June 8 (even though I go through the door and initiate this event multiple times per day.

![image](https://github.com/imhotep/hass-unifi-access/assets/20018778/fa33445d-9f00-45ed-9269-b590c27d08b8)

**Comment by imhotep** [comment] 2024-07-11 03:27
@JDogg016 events only work `without` polling enabled. Do you have polling enabled?

**Comment by JDogg016** [comment] 2024-07-11 05:43
It would seem so, unless there is a different polling option somewhere else.

![image](https://github.com/imhotep/hass-unifi-access/assets/20018778/51d40481-6e7d-494e-88c8-7ef363fd8cd5)

**Comment by imhotep** [comment] 2024-07-11 15:17
@JDogg016 I was asking about whether the integration uses polling to fetch data (vs websocket). Home Assistant will pull entities for updates by default. The only way to find out is to remove the integration and add it back (reconfigure it). I may add a Configure screen at some point to enable changing behavior after adding the integration.

**Comment by jasonhollis** [comment] 2024-07-13 03:57
It does not look like simply disabling polling sorted me out.  I'm getting no notifications now.

**Comment by imhotep** [comment] 2024-07-13 14:21
@jasonhollis How did you disable polling? Again if it’s on the screen that @JDogg016 posted, that won’t do anything useful. It has to be done when the integration is initially set up. So you have to remove the integration and add it again.
Short of more logs I won’t be able to do much and I can’t reproduce the issue in my setup.

**Comment by JDogg016** [comment] 2024-07-15 08:16
I removed and reloaded the configuration with the same result.  No entry/exit logs.  No doorbell logs either.

**Comment by imhotep** [comment] 2024-07-15 14:40
@JDogg016 again without logs I won’t be able to do much. Please provide those.

**Comment by JDogg016** [comment] 2024-07-16 06:54
This is resolved. My apologies as I misread your prior post and enabled polling when I reinstalled the add-on. 

Disabling polling brought the event logging back. You may close the comments if you feel necessary and thank you for your prompt reply.

**Comment by jasonhollis** [comment] 2024-07-16 07:54
Team,

My installation is remote. I can easily hit the box via Tailscale, but I can't run around opening doors, so I have to wait for events.  I have uninstalled and reinstalled it without polling on.  I have not uninstalled HACS.  Short of running debug logging from the integration for a long period, how should I configure the logging?  I'm assuming that with the proper configuration, I should be able to go to /configs/home-assistant.log?  
[home-assistant.log](https://github.com/user-attachments/files/16244988/home-assistant.log)
[custom_components.unifi_access.hub.log](https://github.com/user-attachments/files/16244991/custom_components.unifi_access.hub.log)

Does this look correct from config.yaml:

logger:
  default: info
  logs:
    custom_components.unifi_access.coordinator: debug
    custom_components.hacs: info
    aiogithubapi: info

**Comment by imhotep** [comment] 2024-07-16 16:08
@jasonhollis the easiest way is to:
- Go to the integration page
- Click on Enable debug logging
- Open door/gate either physically or via app/home assistant
- Click on Disable debug logging
- That prompts you to download a log file.
- I need to see that file! Make sure you filter out the lines that don't have `[custom_components.unifi_access.*]` in them

<img width="989" alt="enable logging" src="https://github.com/user-attachments/assets/c0a78e13-5d9f-45fb-9188-2b33d7c2858c">

**Comment by jasonhollis** [comment] 2024-07-17 10:56
I'm not at the location where everything is running, so I can't open the door.  I will be over there in a few days.  I've just left debug logging on, and this is the file:

I do know that this data will represent several unlocks today.  I'm not sure that the doorbell was rung.  Hopefully this provides some sort of insight.  

[custom_components.unifi_access.hub.log](https://github.com/user-attachments/files/16264312/custom_components.unifi_access.hub.log)

**Comment by imhotep** [comment] 2024-07-17 19:27
@jasonhollis it looks like you're not getting any "access.logs.add" (for entry/exits) or "access.remote_view" (doorbell) messages. It will be hard to debug if you're not on site but I could send you a patch in order to get a little more information.

**Comment by imhotep** [comment] 2024-07-25 19:54
@jasonhollis closing this one. Feel free to reopen if/when you have more info.

**Closed by imhotep** 2024-07-25 19:54 UTC
